### ISSUE TITLE
[bug] Head information cannot be recognized by the code

### ISSUE THREAD

**Issue by theAfish** [ruoyuwang1995nya/pfd-kit#74]
Recently, I tried to finetune a model without AIMD. In that case, I should first choose a head for the DP model to go through the exploration process. I have set the "model_frozen_head" and "head" (since I'm not sure which one is which) to "Domains_Alloy" in the "exploration/config" part of the input file.

However, the workflow raised an error in the "expl-ft-blk-dp-test" step, asserting "head must be set for multitask model".

Attached is the error log from the workflow:
[main-log.txt](https://github.com/user-attachments/files/17760725/main-log.txt)

**Comment by ruoyuwang1995nya** [comment]
The code now correctly adds the head setting to the test step
