### ISSUE TITLE
Add README in Examples

### ISSUE THREAD

**Issue by 13yong** [ruoyuwang1995nya/pfd-kit#75]
Hello
How about to add a README txt in the examples file ?

Thank you !

**Comment by 13yong** [comment]
I have an another request. Why not write the element carry on one line in the input.json ?

**Comment by Fillianore** [comment]
> Hello How about to add a README txt in the examples file ?
> 
> Thank you !

Sry for the delay on README in examples. We are busy on fixing bugs and writing docs for PFD-kit. As for the concise description for writing the input script of PFD-kit, please check the doc first [https://ruoyuwang1995nya.github.io/pfd-kit/usage/guide-on-script.html](url)

**Comment by Fillianore** [comment]
> I have an another request. Why not write the element carry on one line in the input.json ?

As for this problem, it seems like a tradition from DeepMD-kit and DP-GEN, we may fix it later.  The temporary solution is to collapse the elements in the text editor.
